### ISSUE TITLE
README.md needs run instructions with expected result

### ISSUE THREAD

**Issue by jabowery** [pgliaskovitis/confabulation-engine#2]
Revisiting this repo after a couple of years, I compiled it under Cygwin successfully and ran it with the output in the attached file.  My memory is fuzzy on how to run this correctly.  Is this the expected output?  Did I invoke it correctly?  Where can one find the confabulated sentence completions?

Perhaps the instructions need to include things like:

```
$ cd ../text_data
$ ../build/confabulation_engine
...

```
Along with some description of the expected behavior of a successful installation and execution.

[execoutput.txt](https://github.com/pgliaskovitis/confabulation-engine/files/3363903/execoutput.txt)

**Comment by pgliaskovitis** [comment]
You should copy the confabulation_engine executable from the build directory to the root directory of the repository.

I have updated Readme.md with more specific instructions as well as the final expected sentence completions. 

It defeats the purpose of a README to include the whole output because the executable is reading files and outputting much more intermediate information, if run correctly.
